# Generated by Django 2.2 on 2019-04-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('todo_id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
