# Generated by Django 2.2 on 2019-04-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='userid',
            field=models.CharField(blank=True, default='anudeep', max_length=255),
        ),
    ]
