# Generated by Django 2.2 on 2019-04-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_document_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.CharField(blank=True, default='incomplete', max_length=255),
        ),
    ]
